import { expect, test, type Page } from '@playwright/test'

const frame=(page:Page)=>page.frameLocator('iframe[title="CoBest visual builder canvas"]')
async function pointerDrag(page:Page,selector:ReturnType<ReturnType<typeof frame>['locator']>,dx:number,dy:number){
  const box=await selector.boundingBox()
  expect(box).toBeTruthy()
  await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2)
  await page.mouse.down()
  await page.mouse.move(box!.x+box!.width/2+dx,box!.y+box!.height/2+dy,{steps:8})
  await page.mouse.up()
}

test('canvas Move and resize persist into preview, undo, and a reload',async({page})=>{
  await page.goto('/e2e.html')
  let heading=frame(page).locator('[data-builder-node="hero-title-home"]')
  await heading.click()
  await expect(frame(page).getByRole('button',{name:'Drag to move the selected element'})).toBeVisible()
  await expect(frame(page).locator('.builder-resize-corner')).toBeVisible()
  await pointerDrag(page,frame(page).getByRole('button',{name:'Drag to move the selected element'}),80,40)
  heading=frame(page).locator('[data-builder-node="hero-title-home"]')
  await expect(heading).toHaveCSS('translate','80px 40px')
  const initialSize=Number.parseFloat(await heading.evaluate(el=>getComputedStyle(el).fontSize))
  await frame(page).getByRole('button',{name:'Make text bigger'}).click()
  await expect.poll(async()=>Number.parseFloat(await heading.evaluate(el=>getComputedStyle(el).fontSize))).toBeGreaterThan(initialSize)
  const initialWidth=await heading.evaluate(el=>el.getBoundingClientRect().width)
  await pointerDrag(page,frame(page).locator('.builder-resize-corner'),85,35)
  heading=frame(page).locator('[data-builder-node="hero-title-home"]')
  await expect.poll(async()=>heading.evaluate(el=>el.getBoundingClientRect().width)).toBeGreaterThan(initialWidth+40)
  await page.getByRole('button',{name:'Preview',exact:true}).click()
  await expect(page.frameLocator('iframe[title="CoBest preview"]').locator('.'+ 'cb-geometry-hero-title-home')).toHaveCSS('translate','80px 40px')
  await page.getByRole('button',{name:'Exit preview'}).click()
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await page.reload()
  heading=frame(page).locator('[data-builder-node="hero-title-home"]')
  await expect(heading).toHaveCSS('translate','80px 40px')
  await heading.click()
  await frame(page).getByRole('button',{name:'Reset position and size'}).click()
  await expect(heading).toHaveCSS('translate','none')
  await page.getByRole('button',{name:'Undo'}).click()
  await expect(heading).toHaveCSS('translate','80px 40px')
})
