import { expect, test } from '@playwright/test'

test('professional editor fits canvas, keeps tools compact and reveals advanced styles on demand',async({page})=>{
  await page.setViewportSize({width:1440,height:900})
  await page.goto('/e2e.html')
  await expect(page.getByRole('button',{name:'Fit canvas to workspace'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Show canvas at actual size'})).toBeVisible()
  await expect(page.locator('[data-testid="canvas-zoom"]')).not.toHaveText('100%')
  const stage=await page.locator('.vb-stage').boundingBox()
  const iframe=await page.locator('iframe[title="CoBest visual builder canvas"]').boundingBox()
  expect(stage).toBeTruthy()
  expect(iframe).toBeTruthy()
  expect(iframe!.x).toBeGreaterThanOrEqual(stage!.x-2)
  expect(iframe!.x+iframe!.width).toBeLessThanOrEqual(stage!.x+stage!.width+2)

  const frame=page.frameLocator('iframe[title="CoBest visual builder canvas"]')
  await frame.locator('[data-builder-node="hero-title-home"]').click()
  const overlay=frame.locator('.builder-node-label')
  await expect(overlay).toBeVisible()
  expect((await overlay.boundingBox())!.width).toBeLessThan(205)
  await expect(frame.getByRole('button',{name:'Drag to move the selected element'})).toBeVisible()
  await expect(frame.getByRole('button',{name:'Drag to resize the selected element'})).toBeVisible()
  await expect(frame.locator('.builder-geometry-handle')).toHaveCount(1)
  await expect(page.getByRole('spinbutton',{name:'X'})).toBeVisible()
  await expect(page.getByRole('spinbutton',{name:'Y'})).toBeVisible()
  await expect(page.getByRole('spinbutton',{name:'Text size'})).toBeVisible()
  await expect(page.getByText('CSS class')).toBeHidden()
  await page.getByRole('button',{name:'Advanced styling'}).click()
  await expect(page.getByText('CSS class')).toBeVisible()

  await page.getByRole('button',{name:'Show canvas at actual size'}).click()
  await expect(page.locator('[data-testid="canvas-zoom"]')).toHaveText('100%')
  await page.getByRole('button',{name:'Fit canvas to workspace'}).click()
  await expect(page.locator('[data-testid="canvas-zoom"]')).not.toHaveText('100%')
})
