import React, { useMemo, useState } from 'react'
import { Check, Copy, ExternalLink, FileText, Image as ImageIcon, Package, Pencil, Plus, RefreshCw, Search, Trash2, Upload, Users, X } from 'lucide-react'
import { createResource, deleteResource, publishStore, unpublishStore, updateResource, uploadMedia } from './api.js'

const money=(v,c='PHP')=>new Intl.NumberFormat('en-PH',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0))
const splitCsv=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean)

function Button({children,variant='primary',...props}){return <button className={`btn btn-${variant}`} {...props}>{children}</button>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,onClose,children}){return <div className="modal-backdrop"><div className="modal admin-advanced-modal"><div className="modal-head"><h3>{title}</h3><button onClick={onClose}><X size={20}/></button></div>{children}</div></div>}
function Empty({icon:Icon=Package,title,body}){return <div className="empty-state"><div><Icon size={24}/></div><h3>{title}</h3><p>{body}</p></div>}

export function ProductsManager({products,setProducts,currency='PHP'}) {
  const empty={name:'',description:'',price:'',compare_at_price:'',inventory:'',category:'',brand:'',sku:'',status:'Draft',image_url:'',tags:'',variants:[]}
  const [query,setQuery]=useState('')
  const [status,setStatus]=useState('All')
  const [editing,setEditing]=useState(null)
  const [draft,setDraft]=useState(empty)
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const filtered=useMemo(()=>products.filter(p=>{
    const q=query.toLowerCase().trim()
    return (!q||[p.name,p.description,p.category,p.brand,p.sku].some(v=>String(v||'').toLowerCase().includes(q)))&&(status==='All'||p.status===status)
  }),[products,query,status])
  const openNew=()=>{setEditing('new');setDraft(empty);setError('')}
  const openEdit=p=>{setEditing(p.id);setDraft({...empty,...p,tags:Array.isArray(p.tags)?p.tags.join(', '):p.tags||'',variants:Array.isArray(p.variants)?p.variants:[]});setError('')}
  const save=async()=>{
    if(!draft.name.trim())return setError('Product name is required.')
    setBusy(true);setError('')
    const payload={...draft,price:Number(draft.price||0),compare_at_price:draft.compare_at_price===''?null:Number(draft.compare_at_price),inventory:Number(draft.inventory||0),tags:splitCsv(draft.tags),variants:Array.isArray(draft.variants)?draft.variants:[]}
    delete payload.id;delete payload.user_id;delete payload.created_at;delete payload.updated_at
    try{
      if(editing==='new'){
        const created=await createResource('products',payload);setProducts(prev=>[created,...prev])
      }else{
        const updated=await updateResource('products',editing,payload);setProducts(prev=>prev.map(x=>x.id===editing?updated:x))
      }
      setEditing(null)
    }catch(err){setError(err.message)}finally{setBusy(false)}
  }
  const remove=async p=>{
    if(!window.confirm(`Delete ${p.name}?`))return
    try{await deleteResource('products',p.id);setProducts(prev=>prev.filter(x=>x.id!==p.id))}catch(err){alert(err.message)}
  }
  const addVariant=()=>setDraft(d=>({...d,variants:[...(d.variants||[]),{title:'Default',sku:'',price:Number(d.price||0),inventory:0,option:''}]}))
  const updateVariant=(i,key,value)=>setDraft(d=>({...d,variants:(d.variants||[]).map((v,n)=>n===i?{...v,[key]:['price','inventory'].includes(key)?Number(value||0):value}:v)}))
  const removeVariant=i=>setDraft(d=>({...d,variants:(d.variants||[]).filter((_,n)=>n!==i)}))
  return <div className="page-wrap"><div className="page-head"><div><p className="overline">CATALOG</p><h1>Products</h1><p>Create, edit, price, organize, and archive products.</p></div><Button onClick={openNew}><Plus size={16}/> Add product</Button></div>
    <div className="toolbar"><div className="searchbox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products"/></div><select className="toolbar-select" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Draft</option><option>Archived</option></select></div>
    <div className="table-card"><table><thead><tr><th>Product</th><th>Status</th><th>Inventory</th><th>Category</th><th>Price</th><th/></tr></thead><tbody>{filtered.map((p,i)=><tr key={p.id}><td><div className="product-cell">{p.image_url?<img className="admin-product-image" src={p.image_url} alt=""/>:<div className={`product-thumb thumb-${(i%4)+1}`}><Package size={18}/></div>}<div><strong>{p.name}</strong><span>{p.sku||p.brand||''}</span></div></div></td><td><span className={`status ${String(p.status||'Draft').toLowerCase()}`}>{p.status||'Draft'}</span></td><td>{p.inventory}</td><td>{p.category||'—'}</td><td>{money(p.price,currency)}</td><td><div className="row-actions"><button onClick={()=>openEdit(p)}><Pencil size={15}/></button><button onClick={()=>remove(p)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<Empty title="No matching products" body="Try a different search/filter or add a product."/>}</div>
    {editing&&<Modal title={editing==='new'?'Add product':'Edit product'} onClose={()=>setEditing(null)}><div className="modal-form">{error&&<div className="auth-message auth-error">{error}</div>}<Field label="Product name"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Description"><textarea rows="4" value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></Field><div className="form-grid three"><Field label="Price"><input type="number" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></Field><Field label="Compare-at price"><input type="number" value={draft.compare_at_price??''} onChange={e=>setDraft({...draft,compare_at_price:e.target.value})}/></Field><Field label="Inventory"><input type="number" value={draft.inventory} onChange={e=>setDraft({...draft,inventory:e.target.value})}/></Field></div><div className="form-grid three"><Field label="Category"><input value={draft.category||''} onChange={e=>setDraft({...draft,category:e.target.value})}/></Field><Field label="Brand"><input value={draft.brand||''} onChange={e=>setDraft({...draft,brand:e.target.value})}/></Field><Field label="SKU"><input value={draft.sku||''} onChange={e=>setDraft({...draft,sku:e.target.value})}/></Field></div><div className="form-grid two"><Field label="Status"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>Draft</option><option>Active</option><option>Archived</option></select></Field><Field label="Tags"><input value={draft.tags||''} onChange={e=>setDraft({...draft,tags:e.target.value})} placeholder="home, featured"/></Field></div><Field label="Primary image URL"><input value={draft.image_url||''} onChange={e=>setDraft({...draft,image_url:e.target.value})} placeholder="https://..."/></Field><div className="variant-editor"><div className="panel-head"><div><span>Variants</span><h3>Options / SKUs</h3></div><Button variant="secondary" onClick={addVariant}><Plus size={14}/> Add variant</Button></div>{(draft.variants||[]).map((v,i)=><div className="variant-row" key={i}><input value={v.title||''} onChange={e=>updateVariant(i,'title',e.target.value)} placeholder="Title"/><input value={v.option||''} onChange={e=>updateVariant(i,'option',e.target.value)} placeholder="e.g. Black / M"/><input value={v.sku||''} onChange={e=>updateVariant(i,'sku',e.target.value)} placeholder="SKU"/><input type="number" value={v.price??0} onChange={e=>updateVariant(i,'price',e.target.value)} placeholder="Price"/><input type="number" value={v.inventory??0} onChange={e=>updateVariant(i,'inventory',e.target.value)} placeholder="Stock"/><button onClick={()=>removeVariant(i)}><Trash2 size={15}/></button></div>)}</div><div className="modal-actions"><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save product'}</Button></div></div></Modal>}
  </div>
}

export function CustomersManager({customers,setCustomers,orders}) {
  const empty={name:'',email:'',phone:'',notes:'',tags:'',marketing_consent:false,address:{}}
  const [query,setQuery]=useState('');const [editing,setEditing]=useState(null);const [draft,setDraft]=useState(empty);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const filtered=customers.filter(c=>!query||[c.name,c.email,c.phone].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))
  const open=x=>{setEditing(x?.id||'new');setDraft(x?{...empty,...x,tags:Array.isArray(x.tags)?x.tags.join(', '):x.tags||''}:empty);setError('')}
  const save=async()=>{if(!draft.name)return;setBusy(true);try{const payload={...draft,tags:splitCsv(draft.tags)};delete payload.id;delete payload.user_id;delete payload.created_at;delete payload.updated_at;if(editing==='new'){const x=await createResource('customers',payload);setCustomers(p=>[x,...p])}else{const x=await updateResource('customers',editing,payload);setCustomers(p=>p.map(y=>y.id===editing?x:y))}setEditing(null)}catch(err){setError(err.message)}finally{setBusy(false)}}
  const remove=async x=>{if(!window.confirm(`Delete ${x.name}?`))return;await deleteResource('customers',x.id);setCustomers(p=>p.filter(y=>y.id!==x.id))}
  return <div className="page-wrap"><div className="page-head"><div><p className="overline">COMMERCE</p><h1>Customers</h1><p>Profiles, purchase history, tags, and marketing consent.</p></div><Button onClick={()=>open()}><Plus size={16}/> Add customer</Button></div><div className="toolbar"><div className="searchbox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customers"/></div></div><div className="table-card"><table><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Orders</th><th>Spent</th><th/></tr></thead><tbody>{filtered.map(c=>{const history=orders.filter(o=>o.customer_id===c.id);const spent=history.filter(o=>o.payment_status==='Paid').reduce((s,o)=>s+Number(o.total||0),0);return <tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email||'—'}</td><td>{c.phone||'—'}</td><td>{history.length}</td><td>{money(spent)}</td><td><div className="row-actions"><button onClick={()=>open(c)}><Pencil size={15}/></button><button onClick={()=>remove(c)}><Trash2 size={15}/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<Empty icon={Users} title="No customers" body="Customer records from checkout will appear here."/>}</div>{editing&&<Modal title={editing==='new'?'Add customer':'Edit customer'} onClose={()=>setEditing(null)}><div className="modal-form">{error&&<div className="auth-message auth-error">{error}</div>}<Field label="Name"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Email"><input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></Field><Field label="Phone"><input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></Field><Field label="Tags"><input value={draft.tags||''} onChange={e=>setDraft({...draft,tags:e.target.value})}/></Field><label className="check-row"><input type="checkbox" checked={!!draft.marketing_consent} onChange={e=>setDraft({...draft,marketing_consent:e.target.checked})}/> Marketing consent</label><Field label="Notes"><textarea rows="4" value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><div className="customer-history"><strong>Order history</strong>{orders.filter(o=>o.customer_id===draft.id).map(o=><span key={o.id}>{o.order_number} · {money(o.total)} · {o.payment_status}</span>)}</div><div className="modal-actions"><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save customer'}</Button></div></div></Modal>}</div>
}

export function OrdersManager({orders,setOrders,customers}) {
  const [query,setQuery]=useState('');const [editing,setEditing]=useState(null);const [draft,setDraft]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const filtered=orders.filter(o=>!query||[o.order_number,o.payment_status,o.fulfillment_status,customers.find(c=>c.id===o.customer_id)?.name].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))
  const edit=o=>{setEditing(o.id);setDraft({...o});setError('')}
  const save=async()=>{setBusy(true);try{const payload={payment_status:draft.payment_status,fulfillment_status:draft.fulfillment_status,tracking_number:draft.tracking_number||'',carrier:draft.carrier||'',notes:draft.notes||''};const x=await updateResource('orders',editing,payload);setOrders(p=>p.map(y=>y.id===editing?x:y));setEditing(null)}catch(err){setError(err.message)}finally{setBusy(false)}}
  const remove=async o=>{if(!window.confirm(`Delete order ${o.order_number}?`))return;await deleteResource('orders',o.id);setOrders(p=>p.filter(x=>x.id!==o.id))}
  return <div className="page-wrap"><div className="page-head"><div><p className="overline">COMMERCE</p><h1>Orders</h1><p>Payment, fulfillment, customer, items, and tracking.</p></div></div><div className="toolbar"><div className="searchbox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search orders"/></div></div><div className="table-card"><table><thead><tr><th>Order</th><th>Customer</th><th>Payment</th><th>Fulfillment</th><th>Total</th><th/></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><strong>{o.order_number||'#'+o.id}</strong></td><td>{customers.find(c=>c.id===o.customer_id)?.name||'Guest'}</td><td>{o.payment_status}</td><td>{o.fulfillment_status}</td><td>{money(o.total)}</td><td><div className="row-actions"><button onClick={()=>edit(o)}><Pencil size={15}/></button><button onClick={()=>remove(o)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<Empty title="No orders" body="Published-store orders will appear here."/>}</div>{editing&&draft&&<Modal title={draft.order_number||'Order'} onClose={()=>setEditing(null)}><div className="modal-form">{error&&<div className="auth-message auth-error">{error}</div>}<div className="order-items"><strong>Items</strong>{(draft.items||[]).map((x,i)=><span key={i}>{x.quantity} × {x.name} — {money(x.line_total)}</span>)}</div><div className="form-grid two"><Field label="Payment status"><select value={draft.payment_status} onChange={e=>setDraft({...draft,payment_status:e.target.value})}><option>Pending</option><option>Paid</option><option>Refunded</option><option>Failed</option></select></Field><Field label="Fulfillment"><select value={draft.fulfillment_status} onChange={e=>setDraft({...draft,fulfillment_status:e.target.value})}><option>Unfulfilled</option><option>Processing</option><option>Fulfilled</option><option>Cancelled</option></select></Field></div><div className="form-grid two"><Field label="Carrier"><input value={draft.carrier||''} onChange={e=>setDraft({...draft,carrier:e.target.value})}/></Field><Field label="Tracking number"><input value={draft.tracking_number||''} onChange={e=>setDraft({...draft,tracking_number:e.target.value})}/></Field></div><Field label="Notes"><textarea rows="4" value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><div className="order-summary"><span>Subtotal <b>{money(draft.subtotal||draft.total)}</b></span><span>Discount <b>-{money(draft.discount_amount)}</b></span><span>Shipping <b>{money(draft.shipping_amount)}</b></span><span>Tax <b>{money(draft.tax_amount)}</b></span><strong>Total <b>{money(draft.total)}</b></strong></div><div className="modal-actions"><Button variant="secondary" onClick={()=>window.print()}>Print</Button><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save order'}</Button></div></div></Modal>}</div>
}

export function MediaManager({items,setItems}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const x=await uploadMedia(file);if(x)setItems(p=>[x,...p])}catch(err){setError(err.message)}finally{setBusy(false);e.target.value=''}}
  const remove=async item=>{if(!window.confirm(`Delete media record ${item.name}?`))return;await deleteResource('media_assets',item.id);setItems(p=>p.filter(x=>x.id!==item.id))}
  return <div className="page-wrap"><div className="page-head"><div><p className="overline">CONTENT</p><h1>Media</h1><p>Upload images, PDFs, and supported media directly to CoBest storage.</p></div><label className="btn btn-primary file-button"><Upload size={16}/>{busy?'Uploading…':'Upload media'}<input type="file" disabled={busy} onChange={upload}/></label></div>{error&&<div className="auth-message auth-error">{error}</div>}<div className="media-grid">{items.map(m=><article className="media-card" key={m.id}>{String(m.mime_type||'').startsWith('image')?<img src={m.url} alt={m.name}/>:<div className="media-file"><FileText size={28}/></div>}<strong>{m.name}</strong><div><a href={m.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a><button onClick={()=>{navigator.clipboard?.writeText(m.url)}}><Copy size={14}/></button><button onClick={()=>remove(m)}><Trash2 size={14}/></button></div></article>)}</div>{!items.length&&<Empty icon={ImageIcon} title="No media yet" body="Upload your first image or file."/>}</div>
}

export function PublishingSettings({workspace,onWorkspace,snapshot}) {
  const [form,setForm]=useState({
    slug:workspace?.slug||'',
    custom_domain:workspace?.custom_domain||'',
    currency:workspace?.currency||'PHP',
    timezone:workspace?.timezone||'Asia/Manila',
    shippingFlat:Number(workspace?.settings?.shippingFlat||0),
    taxRate:Number(workspace?.settings?.taxRate||0)
  })
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
  const publish=async()=>{setBusy(true);setError('');setMessage('');try{const payload={slug:form.slug,custom_domain:form.custom_domain,snapshot:{...snapshot,settings:{...(snapshot.settings||{}),...form}}};const result=await publishStore(payload);setMessage(`Published: ${window.location.origin}${result.store_url}`);onWorkspace?.({...workspace,...form,is_published:true,published_at:new Date().toISOString(),settings:{...(workspace?.settings||{}),shippingFlat:Number(form.shippingFlat||0),taxRate:Number(form.taxRate||0)}})}catch(err){setError(err.message)}finally{setBusy(false)}}
  const unpublish=async()=>{setBusy(true);setError('');try{await unpublishStore();setMessage('Store unpublished.');onWorkspace?.({...workspace,is_published:false})}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="page-wrap"><div className="page-head"><div><p className="overline">PUBLISHING</p><h1>Store settings & publishing</h1><p>Control the public storefront, URL, currency, tax, and shipping defaults.</p></div>{workspace?.is_published&&form.slug&&<a className="btn btn-secondary" href={`/store/${form.slug}`} target="_blank" rel="noreferrer">Open live store <ExternalLink size={14}/></a>}</div>{error&&<div className="auth-message auth-error">{error}</div>}{message&&<div className="auth-message auth-success">{message}</div>}<div className="settings-columns"><section className="panel"><div className="panel-head"><div><span>Store identity</span><h3>Public URL</h3></div></div><Field label="Store slug"><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})} placeholder="my-store"/></Field><Field label="Custom domain"><input value={form.custom_domain} onChange={e=>setForm({...form,custom_domain:e.target.value.toLowerCase().trim()})} placeholder="shop.example.com"/></Field><p className="field-help">Custom domains still require the merchant to point DNS to CoBest before traffic can resolve.</p></section><section className="panel"><div className="panel-head"><div><span>Commerce</span><h3>Defaults</h3></div></div><div className="form-grid two"><Field label="Currency"><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>PHP</option><option>USD</option><option>AUD</option><option>GBP</option><option>EUR</option></select></Field><Field label="Timezone"><input value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field></div><div className="form-grid two"><Field label="Flat shipping"><input type="number" value={form.shippingFlat} onChange={e=>setForm({...form,shippingFlat:Number(e.target.value||0)})}/></Field><Field label="Tax rate %"><input type="number" value={form.taxRate} onChange={e=>setForm({...form,taxRate:Number(e.target.value||0)})}/></Field></div></section></div><div className="publish-bar"><div><span>Status</span><strong>{workspace?.is_published?'Published':'Draft'}</strong></div><div>{workspace?.is_published&&<Button variant="secondary" disabled={busy} onClick={unpublish}>Unpublish</Button>}<Button disabled={busy||!form.slug} onClick={publish}>{busy?'Publishing…':workspace?.is_published?'Publish updates':'Publish store'}</Button></div></div></div>
}

export function InboxManager({subscribers,contacts,bookings,reviews,setReviews}) {
  const [tab,setTab]=useState('contacts')
  const tabs=[['contacts',contacts.length],['subscribers',subscribers.length],['bookings',bookings.length],['reviews',reviews.length]]
  const approve=async review=>{const x=await updateResource('product_reviews',review.id,{status:'Approved'});setReviews(p=>p.map(y=>y.id===review.id?x:y))}
  return <div className="page-wrap"><div className="page-head"><div><p className="overline">INBOX</p><h1>Store activity</h1><p>Messages, subscribers, bookings, and product reviews from the public store.</p></div></div><div className="tab-row">{tabs.map(([id,count])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{id} <b>{count}</b></button>)}</div>{tab==='contacts'&&<div className="table-card"><table><thead><tr><th>Name</th><th>Email</th><th>Message</th><th>Status</th></tr></thead><tbody>{contacts.map(x=><tr key={x.id}><td>{x.name||'—'}</td><td>{x.email}</td><td>{x.message}</td><td>{x.status}</td></tr>)}</tbody></table></div>}{tab==='subscribers'&&<div className="table-card"><table><thead><tr><th>Email</th><th>Joined</th></tr></thead><tbody>{subscribers.map(x=><tr key={x.id}><td>{x.email}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}{tab==='bookings'&&<div className="table-card"><table><thead><tr><th>Name</th><th>Email</th><th>Time</th><th>Status</th></tr></thead><tbody>{bookings.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.email}</td><td>{new Date(x.start_at).toLocaleString()}</td><td>{x.status}</td></tr>)}</tbody></table></div>}{tab==='reviews'&&<div className="table-card"><table><thead><tr><th>Reviewer</th><th>Rating</th><th>Review</th><th>Status</th><th/></tr></thead><tbody>{reviews.map(x=><tr key={x.id}><td>{x.author_name}</td><td>{x.rating}/5</td><td>{x.body}</td><td>{x.status}</td><td>{x.status!=='Approved'&&<button onClick={()=>approve(x)}><Check size={15}/> Approve</button>}</td></tr>)}</tbody></table></div>}</div>
}

export function AnalyticsAdvanced({orders,customers,events,products}) {
  const paid=orders.filter(o=>o.payment_status==='Paid')
  const sales=paid.reduce((s,o)=>s+Number(o.total||0),0)
  const views=events.filter(e=>e.event_type==='page_view').length
  const adds=events.filter(e=>e.event_type==='add_to_cart').length
  const conversion=views?orders.length/views*100:0
  const byProduct={}
  orders.forEach(o=>(o.items||[]).forEach(x=>{byProduct[x.name]=(byProduct[x.name]||0)+Number(x.quantity||0)}))
  const best=Object.entries(byProduct).sort((a,b)=>b[1]-a[1]).slice(0,5)
  return <div className="page-wrap"><div className="page-head"><div><p className="overline">ANALYTICS</p><h1>Store performance</h1><p>Sales, traffic, conversion, and product signals from your published store.</p></div></div><div className="stat-grid"><Stat title="Sales" value={money(sales)} note="Paid revenue"/><Stat title="Orders" value={String(orders.length)} note="All orders"/><Stat title="Store views" value={String(views)} note="Tracked page views"/><Stat title="Conversion" value={views?`${conversion.toFixed(1)}%`:'—'} note="Orders / views"/></div><div className="analytics-grid"><section className="panel"><h3>Top products</h3>{best.map(([name,count])=><div className="metric-row" key={name}><span>{name}</span><strong>{count} sold</strong></div>)}{!best.length&&<p>No order item data yet.</p>}</section><section className="panel"><h3>Commerce</h3><div className="metric-row"><span>Customers</span><strong>{customers.length}</strong></div><div className="metric-row"><span>Products</span><strong>{products.length}</strong></div><div className="metric-row"><span>Add-to-cart events</span><strong>{adds}</strong></div><div className="metric-row"><span>Average paid order</span><strong>{paid.length?money(sales/paid.length):'—'}</strong></div></section></div></div>
}

function Stat({title,value,note}){return <div className="stat-card"><span>{title}</span><strong>{value}</strong><small>{note}</small></div>}
